language: php
php:
  - '7.0'
before_script: composer install
script:
  - ./vendor/bin/phpmd http_server,multiplayer_server,policy_server text unusedcode
  - ./vendor/bin/phpcs --standard=PSR2 http_server multiplayer_server policy_server
